### ISSUE TITLE
Working application name in Alfred V2 Workflow

### ISSUE THREAD

**Issue by palmamartin** [lemonmojo/RoyalTSX_Public#3]
Hi,
in the Alfred V2 Workflow the script responsible for opening a connection uses the wrong application name.

It should be `tell application "Royal TSX"` and not `tell application "RoyalTSX"`

Best,
Martin

**Comment by lemonmojo** [comment]
@mazebuhu Just fixed this in https://github.com/lemonmojo/RoyalTSX_Public/commit/979a7a02b75320eca762bed9a4e8f295329729ce. Thx for reporting!
